version: '3.4'

volumes:
  mysite.db.volume:
    name: mysite.db.volume

services:
  web:
    build: .
    container_name: mysite.web
    ports:
      - "4000:4000"
    command: mix phx.server
    environment:
      - MIX_ENV=dev
      - PORT=4000
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres
    container_name: mysite.db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db

    volumes:
      - mysite.db.volume:/var/lib/postgresql/data
